apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: voting-app-pod
spec:
  containers:
    - name: voting-app-pod
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
